[blue_loadout]
  team_color_id = 34
  custom_color_id = 53
  car_id = 23
  decal_id = 7598
  wheels_id = 10182
  boost_id = 1695
  antenna_id = 0
  hat_id = 0
  paint_finish_id = 0
  custom_finish_id = 0
  engine_audio_id = 4691
  trails_id = 1966
  goal_explosion_id = 8765
  [blue_loadout.paint]
    car_paint_id = 4
    decal_paint_id = 4
    wheels_paint_id = 4
    boost_paint_id = 4
    antenna_paint_id = 0
    hat_paint_id = 0
    trails_paint_id = 12
    goal_explosion_paint_id = 5

[orange_loadout]
  team_color_id = 34
  custom_color_id = 12
  car_id = 23
  decal_id = 4989
  wheels_id = 2614
  boost_id = 2054
  antenna_id = 0
  hat_id = 0
  paint_finish_id = 273
  custom_finish_id = 0
  engine_audio_id = 0
  trails_id = 1966
  goal_explosion_id = 2817
  [orange_loadout.paint]
    car_paint_id = 12
    decal_paint_id = 12
    wheels_paint_id = 3
    boost_paint_id = 3
    antenna_paint_id = 0
    hat_paint_id = 0
    trails_paint_id = 12
    goal_explosion_paint_id = 12
